version: '3.8'

services:
  db:
    image: postgres:17.4
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: quarkus
      POSTGRES_PASSWORD: quarkus
      POSTGRES_DB: quarkusdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: quarkus-app:latest
    container_name: quarkus_app
    depends_on:
      - db
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/quarkusdb
      QUARKUS_DATASOURCE_USERNAME: quarkus
      QUARKUS_DATASOURCE_PASSWORD: quarkus
    ports:
      - "8080:8080"
    build:
      context: ./customer-management
      dockerfile: src/main/docker/Dockerfile.jvm

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app


volumes:
  postgres_data:
