apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-deployment
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: quarkus
  template:
    metadata:
      labels:
        app: quarkus
    spec:
      containers:
        - name: quarkus
          image: jotaven/customer-management-quarkus:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "3Gi"
              cpu: "1500m"
            limits:
              memory: "3500Mi"
              cpu: "2000m"
          env:
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: "jdbc:postgresql://postgres-service:5432/quarkusdb"
            - name: QUARKUS_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
